[functions.salesai-extracted-text]
enabled = true
verify_jwt = false
# import_map = "./functions/salesai-extracted-text/deno.json" # Assuming no specific deno.json, or it's not needed for this function
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/salesai-extracted-text/salesai-extracted-text.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/salesai-extracted-text/*.html" ]
[functions.salesai-analyze-text]
enabled = true
verify_jwt = false # Changed: Server-to-server calls don't use user JWTs
# import_map = "./functions/salesai-analyze-text/deno.json" # Commented out: Not needed for direct API calls
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/salesai-analyze-text/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/salesai-analyze-text/*.html" ]
[functions.extract-text-from-support-pdf]
  enabled = true
  verify_jwt = true
  import_map = "./functions/extract-text-from-support-pdf/deno.json"
  entrypoint = "./functions/extract-text-from-support-pdf/index.ts"

[functions.analyze-embed-support-docs]
  enabled = true
  verify_jwt = false
  import_map = "./functions/analyze-embed-support-docs/deno.json"
  entrypoint = "./functions/analyze-embed-support-docs/index.ts"